Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,9 +35,14 @@ jobs:
             sleep 2
           done
           
-          psql -h postgres -U postgres -c "CREATE DATABASE $DB_NAME;"
-          psql -h postgres -U postgres -c "CREATE ROLE $DB_USER WITH LOGIN PASSWORD '$DB_PASSWORD';"
-          psql -h postgres -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
+          if [ -z "$DB_NAME" ] || [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ]; then
+            echo "One or more required environment variables are not set."
+            exit 1
+          fi
+
+          psql -h postgres -U postgres -c "CREATE DATABASE \"$DB_NAME\";"
+          psql -h postgres -U postgres -c "CREATE ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$DB_PASSWORD';"
+          psql -h postgres -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE \"$DB_NAME\" TO \"$DB_USER\";"
       # - name: Create Database and User
       #   run: |
       #     psql -h postgres -U "$DB_USER" -c "CREATE DATABASE $DB_NAME;"
